# Generated by Django 4.2.11 on 2026-04-05 06:27

import apps.module_3_contacts.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('module_1_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for contact', primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, help_text="Contact person's name", max_length=150)),
                ('phone', models.CharField(db_index=True, help_text='Normalized phone number', max_length=20, validators=[apps.module_3_contacts.models.validate_phone])),
                ('email', models.EmailField(blank=True, help_text='Contact email (optional)', max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this contact was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp')),
                ('user', models.ForeignKey(help_text='User who owns this contact', on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='module_1_auth.customuser')),
            ],
            options={
                'verbose_name_plural': 'Contacts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relationship', models.CharField(blank=True, help_text='Relationship to user (e.g., Mother, Doctor, Friend)', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When marked as emergency contact')),
                ('contact', models.ForeignKey(help_text='Contact marked as emergency', on_delete=django.db.models.deletion.CASCADE, related_name='as_emergency_for', to='module_3_contacts.contact')),
                ('user', models.ForeignKey(help_text='User who has this emergency contact', on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to='module_1_auth.customuser')),
            ],
            options={
                'verbose_name_plural': 'Emergency Contacts',
                'ordering': ['created_at'],
                'unique_together': {('user', 'contact')},
            },
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['user', '-created_at'], name='contact_man_user_id_1951b5_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['user', 'name'], name='contact_man_user_id_d4b4b7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together={('user', 'phone')},
        ),
    ]
