# Generated by Django 4.2.11 on 2026-04-05 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module_3_contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='contact',
            new_name='module_3_co_user_id_87815d_idx',
            old_name='contact_man_user_id_1951b5_idx',
        ),
        migrations.RenameIndex(
            model_name='contact',
            new_name='module_3_co_user_id_b21a8f_idx',
            old_name='contact_man_user_id_d4b4b7_idx',
        ),
    ]
