# Generated by Django 4.2.11 on 2026-04-05 17:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('content', models.TextField()),
                ('variables', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SMSMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender', models.CharField(max_length=15)),
                ('recipient', models.CharField(max_length=15)),
                ('message', models.TextField()),
                ('message_type', models.CharField(choices=[('outbound', 'Outbound'), ('inbound', 'Inbound')], max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed'), ('received', 'Received')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('message_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('characters_count', models.IntegerField(blank=True, null=True)),
                ('segments_count', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['sender', '-created_at'], name='module_2_me_sender_dc6470_idx'), models.Index(fields=['recipient', '-created_at'], name='module_2_me_recipie_404747_idx'), models.Index(fields=['status'], name='module_2_me_status_0778e4_idx')],
            },
        ),
        migrations.CreateModel(
            name='DeliveryStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('accepted', 'Accepted'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('undelivered', 'Undelivered'), ('rejected', 'Rejected')], default='queued', max_length=20)),
                ('status_description', models.TextField(blank=True)),
                ('delivery_timestamp', models.DateTimeField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=100, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('last_checked', models.DateTimeField(auto_now=True)),
                ('check_count', models.IntegerField(default=0)),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_status', to='module_2_messaging.smsmessage')),
            ],
            options={
                'verbose_name_plural': 'Delivery Statuses',
                'ordering': ['-delivery_timestamp'],
            },
        ),
    ]
