# Generated by Django 6.0.4 on 2026-04-12 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_2_messaging', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsmessage',
            name='recipient',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='smsmessage',
            name='sender',
            field=models.CharField(max_length=255),
        ),
    ]
