# Generated by Django 4.2.11 on 2026-04-05 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module_1_auth', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='customuser',
            new_name='module_1_au_phone_6864e0_idx',
            old_name='module_1__auth_u_phone_6f0eb6_idx',
        ),
        migrations.RenameIndex(
            model_name='customuser',
            new_name='module_1_au_email_15ff09_idx',
            old_name='module_1__auth_u_email_7d2e8c_idx',
        ),
        migrations.RenameIndex(
            model_name='customuser',
            new_name='module_1_au_created_1a7a5f_idx',
            old_name='module_1__auth_u_created_d94077_idx',
        ),
        migrations.RenameIndex(
            model_name='otpverification',
            new_name='module_1_au_user_id_f2ba78_idx',
            old_name='module_1__auth_u_user_id_28bed5_idx',
        ),
        migrations.RenameIndex(
            model_name='otpverification',
            new_name='module_1_au_otp_cod_05cd91_idx',
            old_name='module_1__auth_u_otp_cod_112400_idx',
        ),
        migrations.RenameIndex(
            model_name='userloginhistory',
            new_name='module_1_au_user_id_a883b6_idx',
            old_name='module_1__auth_u_user_id_e1182d_idx',
        ),
    ]
